### ISSUE TITLE
Error in ggplot_add(object, p, objectname) :

### ISSUE THREAD

**Issue by limin321** [data2intelligence/SpaCET#15]
I ran into the following error when trying to plot:
```
# plot the QC metrics
SpaCET.visualize.spatialFeature(
  SpaCET_obj, 
  spatialType = "QualityControl", 
  spatialFeatures=c("UMI","Gene")
)
```
<img width="747" alt="Screenshot 2023-06-13 at 8 20 40 PM" src="https://github.com/data2intelligence/SpaCET/assets/42760669/a3d394f6-9497-4791-92b2-015c17956f7a">

Any suggestion on how to troubleshoot it?

Your help is greatly appreciated.

Best,
LC

**Comment by limin321** [comment]
It is solved by loading the "patchwork" package. Thanks.

**Comment by beibeiru** [comment]
Sure. Feel free to let me know if you have any further questions.

Best,
Beibei
