### ISSUE TITLE
Deconvolution Error (Non-conformable Matrix)

### ISSUE THREAD

**Issue by katimbach** [data2intelligence/SpaCET#22]
Hi, 

Thank you so much for your amazing tool! I have been using SpaCET to deconvolute some ovarian cancer Visium samples I have, and so far it has been working great. However, for some reason, for one sample I am getting the following error when I run deconvolution: 
```
SpaCET_obj <- SpaCET.deconvolution(SpaCET_obj, cancerType="OV", coreNo=1)
[1] "Stage 1. Infer malignant cell fraction."
[1] "Stage 1 - Step 1. Clustering."
[1] "Stage 1 - Step 2. Find tumor clusters."
[1] "                  > Use CNA signature: OV"
[1] "Stage 1 - Step 3. Infer malignant cells."
[1] "Stage 2. Hierarchically deconvolve non-malignant cell fracton."
Error: non-conformable matrix dimensions in e1 - Matrix(e2)
```
I haven't experienced this with any other samples thus far, and it wasn't clear from the function source code where this would be coming from. The object format is identical to what I have run up until now (and it has a similar number of spots- 4340), so I'm not sure what's going wrong with this particular sample. Any suggestions on how to mediate this?

**Comment by katimbach** [comment]
Hi beibei, 

Thank you so much for your quick response! I have uploaded the SpaCET R object to the indicated folder. Note that it was originally a Seurat object that I converted using `convert.Seurat()`, and QC has already been run as well. Thank you for your help!!

Best,

Kat

**Comment by beibeiru** [comment]
Hi, @katimbach

I have fixed the bug. Please reinstall our package and run SpaCET on your sample.
Just let me know if you have any further questions.

Best,
Beibei

**Comment by katimbach** [comment]
Hi @beibeiru 

Thank you so much! I re-installed the package and it worked great now. I appreciate your help!!

Best, 

Kat
