### ISSUE TITLE
Release tag for packaging on Bioconda

### ISSUE THREAD

**Issue by dillonroach** [data2intelligence/SpaCET#31]
Hi - I'd love to get this package added to bioconda and a release tag on a specific commit would go a long way toward getting that done; I can take it from there. Thanks!

**Comment by dillonroach** [comment]
@data2intelligence - Hi! Pinging again with the hopes of adding an official release tag to the repo so that packaging on bioconda would be possible, thanks!

**Comment by beibeiru** [comment]
Hi, @dillonroach 

Thanks a lot for your message! A release tag to this repo has been added.

Best,
Beibei

**Comment by dillonroach** [comment]
Thanks so much!
