### ISSUE TITLE
An error raised by SpaCET.quality.control()

### ISSUE THREAD

**Issue by Ron-bio** [data2intelligence/SpaCET#32]
I found that after reading the attached SpaCET object, using spacet.quality.control() will generated an error, as did reading my own ST 10x object.

```
library(SpaCET)
# set the path to the in-house breast cancer ST data. User can set the paths to their own data.
visiumPath <- file.path(system.file(package = "SpaCET"), "extdata/Visium_BC")

# load ST data to create an SpaCET object.
SpaCET_obj <- create.SpaCET.object.10X(visiumPath = visiumPath)

# show this object.
str(SpaCET_obj)

SpaCET_obj@input$counts[1:8,1:6]

# calculate the QC metrics
SpaCET_obj <- SpaCET.quality.control(SpaCET_obj)
```
Error in print.default("Removing spots with less than ", min.genes, " expressed genes.") : 
  invalid 'quote' argument

**Comment by beibeiru** [comment]
Hi, @Ron-bio 

Would you please upload your SpaCET_obj to the following folder? I will fix it soon.
https://connecthkuhk-my.sharepoint.com/:f:/g/personal/bbru_connect_hku_hk/Eo5HeXkhFpFNmDLAIJS25dsBrtopnNEgY4A10Gp5sARhag?e=nPHPZY

Best,
Beibei

**Comment by Ron-bio** [comment]
The SpaCET_obj was loaded from the SpaCET system's extdata file. Nonetheless, a warning was issued during the loading process.
```
> library(SpaCET)
> # set the path to the in-house breast cancer ST data. User can set the paths to their own data.
> visiumPath <- file.path(system.file(package = "SpaCET"), "extdata/Visium_BC")
> # load ST data to create an SpaCET object.
> SpaCET_obj <- create.SpaCET.object.10X(visiumPath = visiumPath)
```
'as(<dgTMatrix>, "dgCMatrix")' is deprecated.
Use 'as(., "CsparseMatrix")' instead.
See help("Deprecated") and help("Matrix-deprecated").

The Matrix package version is 1.7-0. I wonder if this version is causing the problem?


> Hi, @Ron-bio
> 
> Would you please upload your SpaCET_obj to the following folder? I will fix it soon. https://connecthkuhk-my.sharepoint.com/:f:/g/personal/bbru_connect_hku_hk/Eo5HeXkhFpFNmDLAIJS25dsBrtopnNEgY4A10Gp5sARhag?e=nPHPZY
> 
> Best, Beibei

**Comment by beibeiru** [comment]
Hi, @Ron-bio 

Please try again after reinstalling SpaCET. 

```
remove.packages("SpaCET")
devtools::install_github("data2intelligence/SpaCET")
```

Best, Beibei
