### ISSUE TITLE
Normalization for raw count

### ISSUE THREAD

**Issue by xi11** [data2intelligence/SpaCET#33]
Thank you for sharing the spaCET package, it works pretty well for our visium data!

I see in the paper it mentioned that 'The raw count matrices of ST data were normalized to TPM(equivalent to count-permillion CPM for 10x data) to be deconvolved by SpaCET'. I'd like to double check if we need to normalize the raw count to TPM before the deconvolution, SpaCET.deconvolution, or the normalization has been embedded into the function, then we just need to input the raw count matrix.

Thanks!

**Comment by beibeiru** [comment]
Hi, @xi11,

We are delighted that our tool can help your data analysis!
The normalization has been embedded into SpaCET.deconvolution, just input the raw counts to SpaCET.deconvolution.
Feel free to let me know if you have any further questions!

Best,
Beibei
