### ISSUE TITLE
i got  e error . could someone help me? where is the  variable "pp" define ?

### ISSUE THREAD

**Issue by qqq6771020** [data2intelligence/SpaCET#36]
SpaCET.visualize.spatialFeature(SpaCET_obj, spatialType = "Interface")
Error in SpaCET.visualize.spatialFeature(SpaCET_obj, spatialType = "Interface") :
  object 'pp' not found

Is pp a global variable ? 
or in a third-part package?

**Comment by beibeiru** [comment]
Hi, @qqq6771020 

Can you share your SpaCET_obj with me? I will fix it soon.

Best,
Beibei

**Comment by qqq6771020** [comment]
str(SpaCET_obj)
Formal class 'SpaCET' [package "SpaCET"] with 2 slots
  ..@ input  :List of 4
  .. ..$ counts         :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. ..@ i       : int [1:19306621] 21 26 27 32 37 38 39 48 51 52 ...
  .. .. .. ..@ p       : int [1:3814] 0 3893 12222 14137 19405 27527 34242 39881 48552 55472 ...
  .. .. .. ..@ Dim     : int [1:2] 33514 3813
  .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. ..$ : chr [1:33514] "MIR1302-2HG" "FAM138A" "OR4F5" "AL627309.1" ...
  .. .. .. .. ..$ : chr [1:3813] "50x102" "59x19" "14x94" "47x13" ...
  .. .. .. ..@ x       : num [1:19306621] 1 3 20 1 1 1 7 1 1 4 ...
  .. .. .. ..@ factors : list()
  .. ..$ spotCoordinates:'data.frame':  3813 obs. of  3 variables:
  .. .. ..$ pxl_row: num [1:3813] 394 447 183 376 529 ...
  .. .. ..$ pxl_col: num [1:3813] 431 151 405 131 232 ...
  .. .. ..$ barcode: chr [1:3813] "AAACAAGTATCTCCCA-1" "AAACACCAATAACTGC-1" "AAACAGAGCGACTCCT-1" "AAACAGGGTCTATATT-1" ...
  .. ..$ image          :List of 2
  .. .. ..$ path: chr "/lustre/pub/Projects/liuq_proj/NSCLC_end/test/SpaCET-main/inst/extdata/Visium_BC/spatial/tissue_lowres_image.png"
  .. .. ..$ grob:List of 12
  .. .. .. ..$ raster     : 'raster' chr [1:600, 1:600] "#BFC1BD" "#BEC1BD" "#BFC1BE" "#BEC0BD" ...
  .. .. .. ..$ x          : 'simpleUnit' num 0.5npc
  .. .. .. .. ..- attr(*, "unit")= int 0
  .. .. .. ..$ y          : 'simpleUnit' num 0.5npc
  .. .. .. .. ..- attr(*, "unit")= int 0
  .. .. .. ..$ width      : 'simpleUnit' num 1npc
  .. .. .. .. ..- attr(*, "unit")= int 0
  .. .. .. ..$ height     : 'simpleUnit' num 1npc
  .. .. .. .. ..- attr(*, "unit")= int 0
  .. .. .. ..$ just       : chr "centre"
  .. .. .. ..$ hjust      : NULL
  .. .. .. ..$ vjust      : NULL
  .. .. .. ..$ interpolate: logi TRUE
  .. .. .. ..$ name       : chr "GRID.rastergrob.913"
  .. .. .. ..$ gp         : list()
  .. .. .. .. ..- attr(*, "class")= chr "gpar"
  .. .. .. ..$ vp         : NULL
  .. .. .. ..- attr(*, "class")= chr [1:3] "rastergrob" "grob" "gDesc"
  .. ..$ platform       : chr "Visium"
  ..@ results:List of 2
  .. ..$ deconvolution:List of 2
  .. .. ..$ Ref    :List of 3
  .. .. .. ..$ refProfiles: num [1:19093, 1:32] 18.962 0.256 1742.863 1.854 0 ...
  .. .. .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. .. .. ..$ : chr [1:19093] "A1BG" "A1CF" "A2M" "A2ML1" ...
  .. .. .. .. .. ..$ : chr [1:32] "CAF" "Endothelial" "Plasma" "B cell" ...
  .. .. .. ..$ sigGenes   :List of 33
  .. .. .. .. ..$ CAF                       : chr [1:228] "ABCA8" "ABI3BP" "ACTA2" "ADAMTS12" ...
  .. .. .. .. ..$ Endothelial               : chr [1:225] "ABLIM3" "ACE" "ACKR1" "ACVRL1" ...
  .. .. .. .. ..$ Plasma                    : chr [1:243] "AARS" "ACOXL" "ALDH1L2" "ALG14" ...
  .. .. .. .. ..$ B cell                    : chr [1:119] "ADAM28" "AFF3" "AIM2" "ANKRD13A" ...
  .. .. .. .. ..$ T CD4                     : chr [1:59] "AQP3" "BATF" "BCL11B" "CCR4" ...
  .. .. .. .. ..$ T CD8                     : chr [1:51] "APOBEC3C" "APOBEC3G" "CCL5" "CD3D" ...
  .. .. .. .. ..$ NK                        : chr [1:127] "ABHD17A" "ADRB2" "AKR1C3" "APBA2" ...
  .. .. .. .. ..$ cDC                       : chr [1:186] "ACAA1" "ACHE" "ACPP" "ACTN1" ...
  .. .. .. .. ..$ pDC                       : chr [1:229] "ABHD15" "ADA" "AFF3" "AGPAT5" ...
  .. .. .. .. ..$ Macrophage                : chr [1:250] "A2M" "ABCA1" "ACP2" "ACP5" ...
  .. .. .. .. ..$ Mast                      : chr [1:232] "ABCC1" "ABCC4" "ACER3" "ACOT7" ...
  .. .. .. .. ..$ Neutrophil                : chr [1:74] "ABTB1" "ADM" "ALPL" "APOBEC3A" ...
  .. .. .. .. ..$ B cell naive              : chr [1:77] "ABCB4" "ACSM3" "AFF3" "APLP2" ...
  .. .. .. .. ..$ B cell non-switched memory: chr [1:87] "ADAMTS6" "AFF3" "AIM2" "ALOX5" ...
  .. .. .. .. ..$ B cell switched memory    : chr [1:68] "ADAM28" "AHNAK" "AIM2" "AP1S3" ...
  .. .. .. .. ..$ B cell exhausted          : chr [1:58] "AICDA" "AIM2" "ARPC5" "BCAR3" ...
  .. .. .. .. ..$ T CD4 naive               : chr [1:205] "ABLIM1" "ACTN1" "ADTRP" "AIM1" ...
  .. .. .. .. ..$ Th1                       : chr [1:236] "ABCB1" "ABI3" "ADAM19" "ADRB2" ...
  .. .. .. .. ..$ Th2                       : chr [1:52] "AIM1" "ANKRD55" "ANXA1" "BTLA" ...
  .. .. .. .. ..$ Th17                      : chr [1:100] "ADAM12" "ADAM19" "AHR" "ALOX5AP" ...
  .. .. .. .. ..$ Tfh                       : chr [1:235] "ABLIM1" "ADD3" "AGFG1" "AGMAT" ...
  .. .. .. .. ..$ Treg                      : chr [1:301] "ACOT9" "ACP5" "ACTN4" "ADAT2" ...
  .. .. .. .. ..$ T CD8 naive               : chr [1:38] "ADCY1" "ATXN7L3" "CAMK4" "CCR7" ...
  .. .. .. .. ..$ T CD8 central memory      : chr [1:136] "AHNAK" "AIM1" "ANXA1" "AQP3" ...
  .. .. .. .. ..$ T CD8 effector memory     : chr [1:310] "ACAA2" "ACOT7" "ACYP1" "ADRB2" ...
  .. .. .. .. ..$ T CD8 effector            : chr [1:187] "ABCB1" "ABI3" "ADAM8" "ADD3" ...
  .. .. .. .. ..$ T CD8 exhausted           : chr [1:201] "ACP5" "ACTN4" "ACTR3" "AFAP1L2" ...
  .. .. .. .. ..$ cDC1 CLEC9A               : chr [1:214] "ACSL5" "ACTN1" "AGPAT1" "AIM2" ...
  .. .. .. .. ..$ cDC2 CD1C                 : chr [1:266] "ABI3" "AIF1" "AKR1B1" "ALCAM" ...
  .. .. .. .. ..$ cDC3 LAMP3                : chr [1:267] "ABCB10" "ABCC4" "ABTB2" "ACHE" ...
  .. .. .. .. ..$ Macrophage M1             : chr [1:423] "ABI3" "ACSL1" "ADAM28" "ADAM8" ...
  .. .. .. .. ..$ Macrophage M2             : chr [1:230] "A2M" "ABCA1" "ABCC5" "ABCG1" ...
  .. .. .. .. ..$ T cell                    : chr [1:81] "ACAP1" "BATF" "BCL11B" "CAMK4" ...
  .. .. .. ..$ lineageTree:List of 12
  .. .. .. .. ..$ CAF        : chr "CAF"
  .. .. .. .. ..$ Endothelial: chr "Endothelial"
  .. .. .. .. ..$ Plasma     : chr "Plasma"
  .. .. .. .. ..$ B cell     : chr [1:4] "B cell naive" "B cell non-switched memory" "B cell switched memory" "B cell exhausted"
  .. .. .. .. ..$ T CD4      : chr [1:6] "T CD4 naive" "Th1" "Th2" "Th17" ...
  .. .. .. .. ..$ T CD8      : chr [1:5] "T CD8 naive" "T CD8 central memory" "T CD8 effector memory" "T CD8 effector" ...
  .. .. .. .. ..$ NK         : chr "NK"
  .. .. .. .. ..$ cDC        : chr [1:3] "cDC1 CLEC9A" "cDC2 CD1C" "cDC3 LAMP3"
  .. .. .. .. ..$ pDC        : chr "pDC"
  .. .. .. .. ..$ Macrophage : chr [1:2] "Macrophage M1" "Macrophage M2"
  .. .. .. .. ..$ Mast       : chr "Mast"
  .. .. .. .. ..$ Neutrophil : chr "Neutrophil"
  .. .. ..$ propMat: num [1:35, 1:3813] 2.85e-01 3.18e-01 5.34e-02 2.40e-02 1.08e-05 ...
  .. .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. .. ..$ : chr [1:35] "Malignant" "CAF" "Endothelial" "Plasma" ...
  .. .. .. .. ..$ : chr [1:3813] "50x102" "59x19" "14x94" "47x13" ...
  .. ..$ CCI          :List of 1
  .. .. ..$ interface: chr [1, 1:3813] "Stroma" "Tumor" "Stroma" "Stroma" ...
  .. .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. .. ..$ : chr "Interface"
  .. .. .. .. ..$ : chr [1:3813] "50x102" "59x19" "14x94" "47x13" ...

**Comment by beibeiru** [comment]
Hi, 

The code should be 

```
SpaCET.visualize.spatialFeature(SpaCET_obj, spatialType = "Interface", spatialFeature = "Interface")
```

not
```
SpaCET.visualize.spatialFeature(SpaCET_obj, spatialType = c("Interface"))
```

Best,
Beibei

**Comment by 221801007LQLXY** [comment]
Thank you very much for solving my problem; Good luck with your research

**Comment by qqq6771020** [comment]
Thank you very much.
