### ISSUE TITLE
Error in visualSpatial: argument "spotID" is missing, with no default

### ISSUE THREAD

**Issue by Wangmou778** [data2intelligence/SpaCET#39]
When I use SpaCET.SpaCET.      **visualize.cellTypePair(SpaCET_obj,cellTypePair = c("CAF","Macrophage M2"))**     I met an error:

Error in visualSpatial(visiualVector, SpaCET_obj@input$image, SpaCET_obj@input$platform,  : argument "spotID" is missing, with no default

Can you help me?

**Comment by Wangmou778** [comment]
The data I use is the sample data provided by the package

**Comment by beibeiru** [comment]
Hi, @Wangmou778 

Thanks a lot for reporting this bug, which resulted from recent updates.
I have fixed it. Please reinstall our package and try again.

Best,
Beibei

**Comment by Wangmou778** [comment]
Dear beibeiru,

I sincerely appreciate your prompt response and effort in fixing the bug I previously encountered. After applying the updates, I successfully ran the code that had been causing issues before.

Your dedication and support have significantly improved my experience with spaCET, and I’m grateful for the excellent work you’ve put into maintaining this project.

Thank you once again for your hard work!

Best regards,
Wangmou 778

**Comment by beibeiru** [comment]
Hi, @Wangmou778 

I hope our package has been helpful for your project.

Currently, I am developing a new package, which has prompted me to continually add new functions to SpaCET. However, these updates might introduce some unexpected bugs. If you encounter any new issues, please try reinstalling the package or feel free to report them directly to me.

Wishing you great progress in your study!

Best,
Beibei
