### ISSUE TITLE
Error when running SpaCET.CCI.LRNetworkScore

### ISSUE THREAD

**Issue by RYY0722** [data2intelligence/SpaCET#8]
Hi there! Thank you so much for your excellent work!
I got the following error when running the function SpaCET.CCI.LRNetworkScore

Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed

It occurs when running `rownames(LRdb) <- paste0(LRdb[, 1], "_", LRdb[, 2])`  in this function. 

My lineage is defined as follows:
sc_lineageTree = list()
sc_lineageTree[['malignant']] = c("OPC-like","AC-like","S","OC-like","G2M","MES-like")
sc_lineageTree[['myeloid']] = c('myeloid','neutrophil')
sc_lineageTree[['oligodendrocyte']] = c('oligodendrocyte')
sc_lineageTree[['T']] = c('T')

and the celltypes in the sc_annotation are:
> unique(sc_annotation$bio_celltype)
 [1] "myeloid"         "OPC-like"        "neutrophil"      "AC-like"         "S"               "T"              
 [7] "OC-like"         "oligodendrocyte" "G2M"             "MES-like"     

Would you please give me some help regarding this? Thanks a lot!

**Comment by RYY0722** [comment]
Sorry this error is observed when I am running the function **SpaCET.CCI.colocalization**

**Comment by beibeiru** [comment]
Hi, @RYY0722 ,

Would you please deposit your SpaCET_obj in the following folder? I will figure out the issue.

https://connecthkuhk-my.sharepoint.com/:f:/g/personal/bbru_connect_hku_hk/EvJELor_7EZKqDdm9CsQCYABYdjpu-uLxL7KczVAolUlOQ?e=vewika

Thanks.

Best,
Beibei

**Comment by RYY0722** [comment]
@beibeiru I have uploaded. Thanks a lot for your kind attention and help!

**Comment by beibeiru** [comment]
Hi, Yuyan,

Thank you for uploading the data.

I have run SpaCET on your data and don't get any errors. The following link includes my code and results. Please try to reproduce it. Just let me know if you still have any questions. 
https://connecthkuhk-my.sharepoint.com/:w:/g/personal/bbru_connect_hku_hk/ERRWAsESDBVHhMty_5PhyM4Bf1k-5piudJGLgSjXvjA93A?e=klMJWR

BTW, I notice your data is Visium data without H&E image. I strongly recommend using create.SpaCET.object.10X to read your data. You only need to input the “visiumPath” parameter. Please make sure that “visiumPath” points to the standard output folders of 10x SpaCET Ranger, which has both “filtered_feature_bc_matrix” and “spatial” folders.

Best,
Beibei

**Comment by RYY0722** [comment]
@beibeiru Hi Beibei! Thanks a lot for your kind help and checking!

**Comment by RYY0722** [comment]
@beibeiru Hi Beibei, would you help to remove this branch? I think there is not much information for other readers, and it involves some data. Sorry for the inconvenience and thanks a lot for your great work and help!

**Comment by beibeiru** [comment]
I have all information involving your data as well as the shared link. Beibei
