### ISSUE TITLE
Question : celltype per spot 

### ISSUE THREAD

**Issue by justinesjw** [data2intelligence/SpaCET#9]
Dear Beibei, 

Thank you for your enormous effort on SpaCET. I really enjoyed reading your paper and applying your functions on datasets. Everything was precise and straightforward! 

I have some questions to fine tune the results.

May I know if one spot is labelled as either malignant or non malignant cell? 
Here is a result I ran for data from SunnyWu et al publication (BRCA)

![image](https://user-images.githubusercontent.com/26448066/225796125-2040d3f6-104f-4f85-b5d8-17de61848851.png)

I realised that malignant cells are well labelled but other cell types are not very prevalent in the output. 
![image](https://user-images.githubusercontent.com/26448066/225797415-d76915a1-d442-46f0-a0bb-870113d6a176.png)

I am especially interested in the immune population but the scores were not high for multiple samples. Could you please advise me on how to better the results that I currently have? 

I'm using default parameters and here is my sessionInfo()
![image](https://user-images.githubusercontent.com/26448066/225798110-8cc21566-b9f1-416a-8dec-3544924f731b.png)

Thank you for reading through my post!

Best Regards, 
Justine

**Comment by beibeiru** [comment]
Hi, Justine,

Thank you for your interest in our package.

I am afraid that the output of inferred cell type fraction can not be tuned by adjusting any parameters. Also, we do not know the real cell fraction for the ST sample. Thus, it is hard to figure out the reason for low immune fractions. 

BTW, we have added a new parameter `sameScaleForFraction` that can be set as different color scales for each cell type. This would make a better presentation for the low-abundant cell types.

```
library(SpaCET)
SpaCET.visualize.spatialFeature(
     SpaCET_obj, 
     spatialType = "CellFraction", 
     spatialFeatures="All", 
     sameScaleForFraction=FALSE,
     pointSize = 0.1, 
     nrow=5,
     imageBg = FALSE
)
```

<img width="1904" alt="Screenshot 2023-03-17 at 9 20 58 PM" src="https://user-images.githubusercontent.com/33799867/226076596-8ddb728c-ee18-47e3-a186-3ca4c4f45865.png">

Thanks.

Best,
Beibei
